-- SQL to create arXiv bot users
-- Run this in Supabase SQL Editor

INSERT INTO users (orcid_id, name, bio, is_bot, bot_category, onboarding_completed)
VALUES
  ('bot_arxiv_astro_ph', 'arXiv Astrophysics', 'Automatically shares new papers from arXiv astro-ph (Astrophysics)', true, 'astro-ph', true),
  ('bot_arxiv_astro_ph_co', 'arXiv Cosmology and Nongalactic Astrophysics', 'Automatically shares new papers from arXiv astro-ph.CO (Cosmology and Nongalactic Astrophysics)', true, 'astro-ph.CO', true),
  ('bot_arxiv_astro_ph_ep', 'arXiv Earth and Planetary Astrophysics', 'Automatically shares new papers from arXiv astro-ph.EP (Earth and Planetary Astrophysics)', true, 'astro-ph.EP', true),
  ('bot_arxiv_astro_ph_ga', 'arXiv Astrophysics of Galaxies', 'Automatically shares new papers from arXiv astro-ph.GA (Astrophysics of Galaxies)', true, 'astro-ph.GA', true),
  ('bot_arxiv_astro_ph_he', 'arXiv High Energy Astrophysical Phenomena', 'Automatically shares new papers from arXiv astro-ph.HE (High Energy Astrophysical Phenomena)', true, 'astro-ph.HE', true),
  ('bot_arxiv_astro_ph_im', 'arXiv Instrumentation and Methods', 'Automatically shares new papers from arXiv astro-ph.IM (Instrumentation and Methods)', true, 'astro-ph.IM', true),
  ('bot_arxiv_astro_ph_sr', 'arXiv Solar and Stellar Astrophysics', 'Automatically shares new papers from arXiv astro-ph.SR (Solar and Stellar Astrophysics)', true, 'astro-ph.SR', true),
  ('bot_arxiv_cond_mat', 'arXiv Condensed Matter', 'Automatically shares new papers from arXiv cond-mat (Condensed Matter)', true, 'cond-mat', true),
  ('bot_arxiv_cond_mat_dis_nn', 'arXiv Disordered Systems and Neural Networks', 'Automatically shares new papers from arXiv cond-mat.dis-nn (Disordered Systems and Neural Networks)', true, 'cond-mat.dis-nn', true),
  ('bot_arxiv_cond_mat_mes_hall', 'arXiv Mesoscale and Nanoscale Physics', 'Automatically shares new papers from arXiv cond-mat.mes-hall (Mesoscale and Nanoscale Physics)', true, 'cond-mat.mes-hall', true),
  ('bot_arxiv_cond_mat_mtrl_sci', 'arXiv Materials Science', 'Automatically shares new papers from arXiv cond-mat.mtrl-sci (Materials Science)', true, 'cond-mat.mtrl-sci', true),
  ('bot_arxiv_cond_mat_other', 'arXiv Other Condensed Matter', 'Automatically shares new papers from arXiv cond-mat.other (Other Condensed Matter)', true, 'cond-mat.other', true),
  ('bot_arxiv_cond_mat_quant_gas', 'arXiv Quantum Gases', 'Automatically shares new papers from arXiv cond-mat.quant-gas (Quantum Gases)', true, 'cond-mat.quant-gas', true),
  ('bot_arxiv_cond_mat_soft', 'arXiv Soft Condensed Matter', 'Automatically shares new papers from arXiv cond-mat.soft (Soft Condensed Matter)', true, 'cond-mat.soft', true),
  ('bot_arxiv_cond_mat_stat_mech', 'arXiv Statistical Mechanics', 'Automatically shares new papers from arXiv cond-mat.stat-mech (Statistical Mechanics)', true, 'cond-mat.stat-mech', true),
  ('bot_arxiv_cond_mat_str_el', 'arXiv Strongly Correlated Electrons', 'Automatically shares new papers from arXiv cond-mat.str-el (Strongly Correlated Electrons)', true, 'cond-mat.str-el', true),
  ('bot_arxiv_cond_mat_supr_con', 'arXiv Superconductivity', 'Automatically shares new papers from arXiv cond-mat.supr-con (Superconductivity)', true, 'cond-mat.supr-con', true),
  ('bot_arxiv_gr_qc', 'arXiv General Relativity and Quantum Cosmology', 'Automatically shares new papers from arXiv gr-qc (General Relativity and Quantum Cosmology)', true, 'gr-qc', true),
  ('bot_arxiv_hep_ex', 'arXiv High Energy Physics - Experiment', 'Automatically shares new papers from arXiv hep-ex (High Energy Physics - Experiment)', true, 'hep-ex', true),
  ('bot_arxiv_hep_lat', 'arXiv High Energy Physics - Lattice', 'Automatically shares new papers from arXiv hep-lat (High Energy Physics - Lattice)', true, 'hep-lat', true),
  ('bot_arxiv_hep_ph', 'arXiv High Energy Physics - Phenomenology', 'Automatically shares new papers from arXiv hep-ph (High Energy Physics - Phenomenology)', true, 'hep-ph', true),
  ('bot_arxiv_hep_th', 'arXiv High Energy Physics - Theory', 'Automatically shares new papers from arXiv hep-th (High Energy Physics - Theory)', true, 'hep-th', true),
  ('bot_arxiv_math_ph', 'arXiv Mathematical Physics', 'Automatically shares new papers from arXiv math-ph (Mathematical Physics)', true, 'math-ph', true),
  ('bot_arxiv_nlin', 'arXiv Nonlinear Sciences', 'Automatically shares new papers from arXiv nlin (Nonlinear Sciences)', true, 'nlin', true),
  ('bot_arxiv_nlin_ao', 'arXiv Adaptation and Self-Organizing Systems', 'Automatically shares new papers from arXiv nlin.AO (Adaptation and Self-Organizing Systems)', true, 'nlin.AO', true),
  ('bot_arxiv_nlin_cd', 'arXiv Chaotic Dynamics', 'Automatically shares new papers from arXiv nlin.CD (Chaotic Dynamics)', true, 'nlin.CD', true),
  ('bot_arxiv_nlin_cg', 'arXiv Cellular Automata and Lattice Gases', 'Automatically shares new papers from arXiv nlin.CG (Cellular Automata and Lattice Gases)', true, 'nlin.CG', true),
  ('bot_arxiv_nlin_ps', 'arXiv Pattern Formation and Solitons', 'Automatically shares new papers from arXiv nlin.PS (Pattern Formation and Solitons)', true, 'nlin.PS', true),
  ('bot_arxiv_nlin_si', 'arXiv Exactly Solvable and Integrable Systems', 'Automatically shares new papers from arXiv nlin.SI (Exactly Solvable and Integrable Systems)', true, 'nlin.SI', true),
  ('bot_arxiv_nucl_ex', 'arXiv Nuclear Experiment', 'Automatically shares new papers from arXiv nucl-ex (Nuclear Experiment)', true, 'nucl-ex', true),
  ('bot_arxiv_nucl_th', 'arXiv Nuclear Theory', 'Automatically shares new papers from arXiv nucl-th (Nuclear Theory)', true, 'nucl-th', true),
  ('bot_arxiv_physics', 'arXiv Physics', 'Automatically shares new papers from arXiv physics (Physics)', true, 'physics', true),
  ('bot_arxiv_physics_acc_ph', 'arXiv Accelerator Physics', 'Automatically shares new papers from arXiv physics.acc-ph (Accelerator Physics)', true, 'physics.acc-ph', true),
  ('bot_arxiv_physics_ao_ph', 'arXiv Atmospheric and Oceanic Physics', 'Automatically shares new papers from arXiv physics.ao-ph (Atmospheric and Oceanic Physics)', true, 'physics.ao-ph', true),
  ('bot_arxiv_physics_app_ph', 'arXiv Applied Physics', 'Automatically shares new papers from arXiv physics.app-ph (Applied Physics)', true, 'physics.app-ph', true),
  ('bot_arxiv_physics_atm_clus', 'arXiv Atomic and Molecular Clusters', 'Automatically shares new papers from arXiv physics.atm-clus (Atomic and Molecular Clusters)', true, 'physics.atm-clus', true),
  ('bot_arxiv_physics_atom_ph', 'arXiv Atomic Physics', 'Automatically shares new papers from arXiv physics.atom-ph (Atomic Physics)', true, 'physics.atom-ph', true),
  ('bot_arxiv_physics_bio_ph', 'arXiv Biological Physics', 'Automatically shares new papers from arXiv physics.bio-ph (Biological Physics)', true, 'physics.bio-ph', true),
  ('bot_arxiv_physics_chem_ph', 'arXiv Chemical Physics', 'Automatically shares new papers from arXiv physics.chem-ph (Chemical Physics)', true, 'physics.chem-ph', true),
  ('bot_arxiv_physics_class_ph', 'arXiv Classical Physics', 'Automatically shares new papers from arXiv physics.class-ph (Classical Physics)', true, 'physics.class-ph', true),
  ('bot_arxiv_physics_comp_ph', 'arXiv Computational Physics', 'Automatically shares new papers from arXiv physics.comp-ph (Computational Physics)', true, 'physics.comp-ph', true),
  ('bot_arxiv_physics_data_an', 'arXiv Data Analysis, Statistics and Probability', 'Automatically shares new papers from arXiv physics.data-an (Data Analysis, Statistics and Probability)', true, 'physics.data-an', true),
  ('bot_arxiv_physics_ed_ph', 'arXiv Physics Education', 'Automatically shares new papers from arXiv physics.ed-ph (Physics Education)', true, 'physics.ed-ph', true),
  ('bot_arxiv_physics_flu_dyn', 'arXiv Fluid Dynamics', 'Automatically shares new papers from arXiv physics.flu-dyn (Fluid Dynamics)', true, 'physics.flu-dyn', true),
  ('bot_arxiv_physics_gen_ph', 'arXiv General Physics', 'Automatically shares new papers from arXiv physics.gen-ph (General Physics)', true, 'physics.gen-ph', true),
  ('bot_arxiv_physics_geo_ph', 'arXiv Geophysics', 'Automatically shares new papers from arXiv physics.geo-ph (Geophysics)', true, 'physics.geo-ph', true),
  ('bot_arxiv_physics_hist_ph', 'arXiv History and Philosophy of Physics', 'Automatically shares new papers from arXiv physics.hist-ph (History and Philosophy of Physics)', true, 'physics.hist-ph', true),
  ('bot_arxiv_physics_ins_det', 'arXiv Instrumentation and Detectors', 'Automatically shares new papers from arXiv physics.ins-det (Instrumentation and Detectors)', true, 'physics.ins-det', true),
  ('bot_arxiv_physics_med_ph', 'arXiv Medical Physics', 'Automatically shares new papers from arXiv physics.med-ph (Medical Physics)', true, 'physics.med-ph', true),
  ('bot_arxiv_physics_optics', 'arXiv Optics', 'Automatically shares new papers from arXiv physics.optics (Optics)', true, 'physics.optics', true),
  ('bot_arxiv_physics_plasm_ph', 'arXiv Plasma Physics', 'Automatically shares new papers from arXiv physics.plasm-ph (Plasma Physics)', true, 'physics.plasm-ph', true),
  ('bot_arxiv_physics_pop_ph', 'arXiv Popular Physics', 'Automatically shares new papers from arXiv physics.pop-ph (Popular Physics)', true, 'physics.pop-ph', true),
  ('bot_arxiv_physics_soc_ph', 'arXiv Physics and Society', 'Automatically shares new papers from arXiv physics.soc-ph (Physics and Society)', true, 'physics.soc-ph', true),
  ('bot_arxiv_physics_space_ph', 'arXiv Space Physics', 'Automatically shares new papers from arXiv physics.space-ph (Space Physics)', true, 'physics.space-ph', true),
  ('bot_arxiv_quant_ph', 'arXiv Quantum Physics', 'Automatically shares new papers from arXiv quant-ph (Quantum Physics)', true, 'quant-ph', true),
  ('bot_arxiv_math_ac', 'arXiv Commutative Algebra', 'Automatically shares new papers from arXiv math.AC (Commutative Algebra)', true, 'math.AC', true),
  ('bot_arxiv_math_ag', 'arXiv Algebraic Geometry', 'Automatically shares new papers from arXiv math.AG (Algebraic Geometry)', true, 'math.AG', true),
  ('bot_arxiv_math_ap', 'arXiv Analysis of PDEs', 'Automatically shares new papers from arXiv math.AP (Analysis of PDEs)', true, 'math.AP', true),
  ('bot_arxiv_math_at', 'arXiv Algebraic Topology', 'Automatically shares new papers from arXiv math.AT (Algebraic Topology)', true, 'math.AT', true),
  ('bot_arxiv_math_ca', 'arXiv Classical Analysis and ODEs', 'Automatically shares new papers from arXiv math.CA (Classical Analysis and ODEs)', true, 'math.CA', true),
  ('bot_arxiv_math_co', 'arXiv Combinatorics', 'Automatically shares new papers from arXiv math.CO (Combinatorics)', true, 'math.CO', true),
  ('bot_arxiv_math_ct', 'arXiv Category Theory', 'Automatically shares new papers from arXiv math.CT (Category Theory)', true, 'math.CT', true),
  ('bot_arxiv_math_cv', 'arXiv Complex Variables', 'Automatically shares new papers from arXiv math.CV (Complex Variables)', true, 'math.CV', true),
  ('bot_arxiv_math_dg', 'arXiv Differential Geometry', 'Automatically shares new papers from arXiv math.DG (Differential Geometry)', true, 'math.DG', true),
  ('bot_arxiv_math_ds', 'arXiv Dynamical Systems', 'Automatically shares new papers from arXiv math.DS (Dynamical Systems)', true, 'math.DS', true),
  ('bot_arxiv_math_fa', 'arXiv Functional Analysis', 'Automatically shares new papers from arXiv math.FA (Functional Analysis)', true, 'math.FA', true),
  ('bot_arxiv_math_gm', 'arXiv General Mathematics', 'Automatically shares new papers from arXiv math.GM (General Mathematics)', true, 'math.GM', true),
  ('bot_arxiv_math_gn', 'arXiv General Topology', 'Automatically shares new papers from arXiv math.GN (General Topology)', true, 'math.GN', true),
  ('bot_arxiv_math_gr', 'arXiv Group Theory', 'Automatically shares new papers from arXiv math.GR (Group Theory)', true, 'math.GR', true),
  ('bot_arxiv_math_gt', 'arXiv Geometric Topology', 'Automatically shares new papers from arXiv math.GT (Geometric Topology)', true, 'math.GT', true),
  ('bot_arxiv_math_ho', 'arXiv History and Overview', 'Automatically shares new papers from arXiv math.HO (History and Overview)', true, 'math.HO', true),
  ('bot_arxiv_math_it', 'arXiv Information Theory', 'Automatically shares new papers from arXiv math.IT (Information Theory)', true, 'math.IT', true),
  ('bot_arxiv_math_kt', 'arXiv K-Theory and Homology', 'Automatically shares new papers from arXiv math.KT (K-Theory and Homology)', true, 'math.KT', true),
  ('bot_arxiv_math_lo', 'arXiv Logic', 'Automatically shares new papers from arXiv math.LO (Logic)', true, 'math.LO', true),
  ('bot_arxiv_math_mg', 'arXiv Metric Geometry', 'Automatically shares new papers from arXiv math.MG (Metric Geometry)', true, 'math.MG', true),
  ('bot_arxiv_math_mp', 'arXiv Mathematical Physics', 'Automatically shares new papers from arXiv math.MP (Mathematical Physics)', true, 'math.MP', true),
  ('bot_arxiv_math_na', 'arXiv Numerical Analysis', 'Automatically shares new papers from arXiv math.NA (Numerical Analysis)', true, 'math.NA', true),
  ('bot_arxiv_math_nt', 'arXiv Number Theory', 'Automatically shares new papers from arXiv math.NT (Number Theory)', true, 'math.NT', true),
  ('bot_arxiv_math_oa', 'arXiv Operator Algebras', 'Automatically shares new papers from arXiv math.OA (Operator Algebras)', true, 'math.OA', true),
  ('bot_arxiv_math_oc', 'arXiv Optimization and Control', 'Automatically shares new papers from arXiv math.OC (Optimization and Control)', true, 'math.OC', true),
  ('bot_arxiv_math_pr', 'arXiv Probability', 'Automatically shares new papers from arXiv math.PR (Probability)', true, 'math.PR', true),
  ('bot_arxiv_math_qa', 'arXiv Quantum Algebra', 'Automatically shares new papers from arXiv math.QA (Quantum Algebra)', true, 'math.QA', true),
  ('bot_arxiv_math_ra', 'arXiv Rings and Algebras', 'Automatically shares new papers from arXiv math.RA (Rings and Algebras)', true, 'math.RA', true),
  ('bot_arxiv_math_rt', 'arXiv Representation Theory', 'Automatically shares new papers from arXiv math.RT (Representation Theory)', true, 'math.RT', true),
  ('bot_arxiv_math_sg', 'arXiv Symplectic Geometry', 'Automatically shares new papers from arXiv math.SG (Symplectic Geometry)', true, 'math.SG', true),
  ('bot_arxiv_math_sp', 'arXiv Spectral Theory', 'Automatically shares new papers from arXiv math.SP (Spectral Theory)', true, 'math.SP', true),
  ('bot_arxiv_math_st', 'arXiv Statistics Theory', 'Automatically shares new papers from arXiv math.ST (Statistics Theory)', true, 'math.ST', true),
  ('bot_arxiv_cs_ai', 'arXiv Artificial Intelligence', 'Automatically shares new papers from arXiv cs.AI (Artificial Intelligence)', true, 'cs.AI', true),
  ('bot_arxiv_cs_ar', 'arXiv Hardware Architecture', 'Automatically shares new papers from arXiv cs.AR (Hardware Architecture)', true, 'cs.AR', true),
  ('bot_arxiv_cs_cc', 'arXiv Computational Complexity', 'Automatically shares new papers from arXiv cs.CC (Computational Complexity)', true, 'cs.CC', true),
  ('bot_arxiv_cs_ce', 'arXiv Computational Engineering, Finance, and Science', 'Automatically shares new papers from arXiv cs.CE (Computational Engineering, Finance, and Science)', true, 'cs.CE', true),
  ('bot_arxiv_cs_cg', 'arXiv Computational Geometry', 'Automatically shares new papers from arXiv cs.CG (Computational Geometry)', true, 'cs.CG', true),
  ('bot_arxiv_cs_cl', 'arXiv Computation and Language', 'Automatically shares new papers from arXiv cs.CL (Computation and Language)', true, 'cs.CL', true),
  ('bot_arxiv_cs_cr', 'arXiv Cryptography and Security', 'Automatically shares new papers from arXiv cs.CR (Cryptography and Security)', true, 'cs.CR', true),
  ('bot_arxiv_cs_cv', 'arXiv Computer Vision and Pattern Recognition', 'Automatically shares new papers from arXiv cs.CV (Computer Vision and Pattern Recognition)', true, 'cs.CV', true),
  ('bot_arxiv_cs_cy', 'arXiv Computers and Society', 'Automatically shares new papers from arXiv cs.CY (Computers and Society)', true, 'cs.CY', true),
  ('bot_arxiv_cs_db', 'arXiv Databases', 'Automatically shares new papers from arXiv cs.DB (Databases)', true, 'cs.DB', true),
  ('bot_arxiv_cs_dc', 'arXiv Distributed, Parallel, and Cluster Computing', 'Automatically shares new papers from arXiv cs.DC (Distributed, Parallel, and Cluster Computing)', true, 'cs.DC', true),
  ('bot_arxiv_cs_dl', 'arXiv Digital Libraries', 'Automatically shares new papers from arXiv cs.DL (Digital Libraries)', true, 'cs.DL', true),
  ('bot_arxiv_cs_dm', 'arXiv Discrete Mathematics', 'Automatically shares new papers from arXiv cs.DM (Discrete Mathematics)', true, 'cs.DM', true),
  ('bot_arxiv_cs_ds', 'arXiv Data Structures and Algorithms', 'Automatically shares new papers from arXiv cs.DS (Data Structures and Algorithms)', true, 'cs.DS', true),
  ('bot_arxiv_cs_et', 'arXiv Emerging Technologies', 'Automatically shares new papers from arXiv cs.ET (Emerging Technologies)', true, 'cs.ET', true),
  ('bot_arxiv_cs_fl', 'arXiv Formal Languages and Automata Theory', 'Automatically shares new papers from arXiv cs.FL (Formal Languages and Automata Theory)', true, 'cs.FL', true),
  ('bot_arxiv_cs_gl', 'arXiv General Literature', 'Automatically shares new papers from arXiv cs.GL (General Literature)', true, 'cs.GL', true),
  ('bot_arxiv_cs_gr', 'arXiv Graphics', 'Automatically shares new papers from arXiv cs.GR (Graphics)', true, 'cs.GR', true),
  ('bot_arxiv_cs_gt', 'arXiv Computer Science and Game Theory', 'Automatically shares new papers from arXiv cs.GT (Computer Science and Game Theory)', true, 'cs.GT', true),
  ('bot_arxiv_cs_hc', 'arXiv Human-Computer Interaction', 'Automatically shares new papers from arXiv cs.HC (Human-Computer Interaction)', true, 'cs.HC', true),
  ('bot_arxiv_cs_ir', 'arXiv Information Retrieval', 'Automatically shares new papers from arXiv cs.IR (Information Retrieval)', true, 'cs.IR', true),
  ('bot_arxiv_cs_it', 'arXiv Information Theory', 'Automatically shares new papers from arXiv cs.IT (Information Theory)', true, 'cs.IT', true),
  ('bot_arxiv_cs_lg', 'arXiv Machine Learning', 'Automatically shares new papers from arXiv cs.LG (Machine Learning)', true, 'cs.LG', true),
  ('bot_arxiv_cs_lo', 'arXiv Logic in Computer Science', 'Automatically shares new papers from arXiv cs.LO (Logic in Computer Science)', true, 'cs.LO', true),
  ('bot_arxiv_cs_ma', 'arXiv Multiagent Systems', 'Automatically shares new papers from arXiv cs.MA (Multiagent Systems)', true, 'cs.MA', true),
  ('bot_arxiv_cs_mm', 'arXiv Multimedia', 'Automatically shares new papers from arXiv cs.MM (Multimedia)', true, 'cs.MM', true),
  ('bot_arxiv_cs_ms', 'arXiv Mathematical Software', 'Automatically shares new papers from arXiv cs.MS (Mathematical Software)', true, 'cs.MS', true),
  ('bot_arxiv_cs_na', 'arXiv Numerical Analysis', 'Automatically shares new papers from arXiv cs.NA (Numerical Analysis)', true, 'cs.NA', true),
  ('bot_arxiv_cs_ne', 'arXiv Neural and Evolutionary Computing', 'Automatically shares new papers from arXiv cs.NE (Neural and Evolutionary Computing)', true, 'cs.NE', true),
  ('bot_arxiv_cs_ni', 'arXiv Networking and Internet Architecture', 'Automatically shares new papers from arXiv cs.NI (Networking and Internet Architecture)', true, 'cs.NI', true),
  ('bot_arxiv_cs_oh', 'arXiv Other Computer Science', 'Automatically shares new papers from arXiv cs.OH (Other Computer Science)', true, 'cs.OH', true),
  ('bot_arxiv_cs_os', 'arXiv Operating Systems', 'Automatically shares new papers from arXiv cs.OS (Operating Systems)', true, 'cs.OS', true),
  ('bot_arxiv_cs_pf', 'arXiv Performance', 'Automatically shares new papers from arXiv cs.PF (Performance)', true, 'cs.PF', true),
  ('bot_arxiv_cs_pl', 'arXiv Programming Languages', 'Automatically shares new papers from arXiv cs.PL (Programming Languages)', true, 'cs.PL', true),
  ('bot_arxiv_cs_ro', 'arXiv Robotics', 'Automatically shares new papers from arXiv cs.RO (Robotics)', true, 'cs.RO', true),
  ('bot_arxiv_cs_sc', 'arXiv Symbolic Computation', 'Automatically shares new papers from arXiv cs.SC (Symbolic Computation)', true, 'cs.SC', true),
  ('bot_arxiv_cs_sd', 'arXiv Sound', 'Automatically shares new papers from arXiv cs.SD (Sound)', true, 'cs.SD', true),
  ('bot_arxiv_cs_se', 'arXiv Software Engineering', 'Automatically shares new papers from arXiv cs.SE (Software Engineering)', true, 'cs.SE', true),
  ('bot_arxiv_cs_si', 'arXiv Social and Information Networks', 'Automatically shares new papers from arXiv cs.SI (Social and Information Networks)', true, 'cs.SI', true),
  ('bot_arxiv_cs_sy', 'arXiv Systems and Control', 'Automatically shares new papers from arXiv cs.SY (Systems and Control)', true, 'cs.SY', true),
  ('bot_arxiv_q_bio_bm', 'arXiv Biomolecules', 'Automatically shares new papers from arXiv q-bio.BM (Biomolecules)', true, 'q-bio.BM', true),
  ('bot_arxiv_q_bio_cb', 'arXiv Cell Behavior', 'Automatically shares new papers from arXiv q-bio.CB (Cell Behavior)', true, 'q-bio.CB', true),
  ('bot_arxiv_q_bio_gn', 'arXiv Genomics', 'Automatically shares new papers from arXiv q-bio.GN (Genomics)', true, 'q-bio.GN', true),
  ('bot_arxiv_q_bio_mn', 'arXiv Molecular Networks', 'Automatically shares new papers from arXiv q-bio.MN (Molecular Networks)', true, 'q-bio.MN', true),
  ('bot_arxiv_q_bio_nc', 'arXiv Neurons and Cognition', 'Automatically shares new papers from arXiv q-bio.NC (Neurons and Cognition)', true, 'q-bio.NC', true),
  ('bot_arxiv_q_bio_ot', 'arXiv Other Quantitative Biology', 'Automatically shares new papers from arXiv q-bio.OT (Other Quantitative Biology)', true, 'q-bio.OT', true),
  ('bot_arxiv_q_bio_pe', 'arXiv Populations and Evolution', 'Automatically shares new papers from arXiv q-bio.PE (Populations and Evolution)', true, 'q-bio.PE', true),
  ('bot_arxiv_q_bio_qm', 'arXiv Quantitative Methods', 'Automatically shares new papers from arXiv q-bio.QM (Quantitative Methods)', true, 'q-bio.QM', true),
  ('bot_arxiv_q_bio_sc', 'arXiv Subcellular Processes', 'Automatically shares new papers from arXiv q-bio.SC (Subcellular Processes)', true, 'q-bio.SC', true),
  ('bot_arxiv_q_bio_to', 'arXiv Tissues and Organs', 'Automatically shares new papers from arXiv q-bio.TO (Tissues and Organs)', true, 'q-bio.TO', true),
  ('bot_arxiv_q_fin_cp', 'arXiv Computational Finance', 'Automatically shares new papers from arXiv q-fin.CP (Computational Finance)', true, 'q-fin.CP', true),
  ('bot_arxiv_q_fin_ec', 'arXiv Economics', 'Automatically shares new papers from arXiv q-fin.EC (Economics)', true, 'q-fin.EC', true),
  ('bot_arxiv_q_fin_gn', 'arXiv General Finance', 'Automatically shares new papers from arXiv q-fin.GN (General Finance)', true, 'q-fin.GN', true),
  ('bot_arxiv_q_fin_mf', 'arXiv Mathematical Finance', 'Automatically shares new papers from arXiv q-fin.MF (Mathematical Finance)', true, 'q-fin.MF', true),
  ('bot_arxiv_q_fin_pm', 'arXiv Portfolio Management', 'Automatically shares new papers from arXiv q-fin.PM (Portfolio Management)', true, 'q-fin.PM', true),
  ('bot_arxiv_q_fin_pr', 'arXiv Pricing of Securities', 'Automatically shares new papers from arXiv q-fin.PR (Pricing of Securities)', true, 'q-fin.PR', true),
  ('bot_arxiv_q_fin_rm', 'arXiv Risk Management', 'Automatically shares new papers from arXiv q-fin.RM (Risk Management)', true, 'q-fin.RM', true),
  ('bot_arxiv_q_fin_st', 'arXiv Statistical Finance', 'Automatically shares new papers from arXiv q-fin.ST (Statistical Finance)', true, 'q-fin.ST', true),
  ('bot_arxiv_q_fin_tr', 'arXiv Trading and Market Microstructure', 'Automatically shares new papers from arXiv q-fin.TR (Trading and Market Microstructure)', true, 'q-fin.TR', true),
  ('bot_arxiv_stat_ap', 'arXiv Applications', 'Automatically shares new papers from arXiv stat.AP (Applications)', true, 'stat.AP', true),
  ('bot_arxiv_stat_co', 'arXiv Computation', 'Automatically shares new papers from arXiv stat.CO (Computation)', true, 'stat.CO', true),
  ('bot_arxiv_stat_me', 'arXiv Methodology', 'Automatically shares new papers from arXiv stat.ME (Methodology)', true, 'stat.ME', true),
  ('bot_arxiv_stat_ml', 'arXiv Machine Learning', 'Automatically shares new papers from arXiv stat.ML (Machine Learning)', true, 'stat.ML', true),
  ('bot_arxiv_stat_ot', 'arXiv Other Statistics', 'Automatically shares new papers from arXiv stat.OT (Other Statistics)', true, 'stat.OT', true),
  ('bot_arxiv_stat_th', 'arXiv Statistics Theory', 'Automatically shares new papers from arXiv stat.TH (Statistics Theory)', true, 'stat.TH', true),
  ('bot_arxiv_eess_as', 'arXiv Audio and Speech Processing', 'Automatically shares new papers from arXiv eess.AS (Audio and Speech Processing)', true, 'eess.AS', true),
  ('bot_arxiv_eess_iv', 'arXiv Image and Video Processing', 'Automatically shares new papers from arXiv eess.IV (Image and Video Processing)', true, 'eess.IV', true),
  ('bot_arxiv_eess_sp', 'arXiv Signal Processing', 'Automatically shares new papers from arXiv eess.SP (Signal Processing)', true, 'eess.SP', true),
  ('bot_arxiv_eess_sy', 'arXiv Systems and Control', 'Automatically shares new papers from arXiv eess.SY (Systems and Control)', true, 'eess.SY', true),
  ('bot_arxiv_econ_em', 'arXiv Econometrics', 'Automatically shares new papers from arXiv econ.EM (Econometrics)', true, 'econ.EM', true),
  ('bot_arxiv_econ_gn', 'arXiv General Economics', 'Automatically shares new papers from arXiv econ.GN (General Economics)', true, 'econ.GN', true),
  ('bot_arxiv_econ_th', 'arXiv Theoretical Economics', 'Automatically shares new papers from arXiv econ.TH (Theoretical Economics)', true, 'econ.TH', true)
ON CONFLICT (orcid_id) DO UPDATE SET
  name = EXCLUDED.name,
  bio = EXCLUDED.bio,
  bot_category = EXCLUDED.bot_category;

-- Total: 159 bot users
